sequenceDiagram
participant Voter
rect rgb(255, 0, 0)
note left of Voter: In Commit State
end
participant SC as SmartContract
Voter->>Blockchain: filterVoterAddedEvents()
Blockchain-->>Voter: IDCList
Voter->>SC: getTreeLevel()
SC-->>Voter: TreeLevel
Voter->>SC: getExtNullifier()
SC-->>Voter: ExtN
Voter->>Voter: genTree(IDCList): MerkleTree
Note over Voter,Voter: Voter uses own stored IDC
Voter->>Voter: constructMerkleProof(MerkleTree, IDC): MerkleProof
Voter->>Voter: genVoteHash(VID, VSk): VH
Voter->>Voter: store(VID, VSk)
Note over Voter: MPI is a component of MerkleProof
Voter->>Voter: genNullifierHash(ExtN, ID, MPI): NH
Voter ->>Voter: sign(VH, PrivK): Signature
Voter ->> IPFS: getFiles(URL)
IPFS -->> Voter: CirC, ProveKey
Voter->>Voter: genWitness(CirC, VH, ID, MerkleProof, TreeLevel, ExtN, Signature): Witness
Voter->>Voter: genProof(Witness, ProveKey): Proof
Voter->>SC: commitVote(VH, Proof, NH)
SC->>SC: verifyProof(VH, Proof, NH, MRS, ExtN)
alt Valid Proof && NH is not registered before
  SC->>SC:store(VoterAddress => VH, NH)
else
  SC->>Voter: fail
end


