sequenceDiagram
participant Proposer
participant SC as Smart Contract
participant BC as Blockchain
rect rgb(255, 0, 0)
note left of Proposer: In Proposal State
end
Proposer ->> SC: propose(Proposal)
alt Proposer is eligible
  note over SC,SC: CID, i.e candidate ID, is initially 0
  SC ->> SC: CID = CID + 1
  SC ->> SC: store(CID)
  SC ->> SC: removeProposer(Proposer)
  SC ->> BC: emit ProposedEvent(CID, Proposal)
else
  SC ->> Proposer: fail
end
