sequenceDiagram
participant Voter
participant SC as SmartContract
participant TallyLib
note left of TallyLib: TallyLib is imported by <br> SmartContract
rect rgb(255, 0, 0)
note left of Voter: In Reveal State
end
Voter->>SC: revealVote(VID, VSk)
Note over Voter, SC: nc is the candidate count
alt 0 < VoteID < nc!-1 AND <br> hash(VID,VSk) == VoterAddress->VH
SC->>SC: delete(VoterAddress->VH)

SC->>TallyLib: tally(CandidateCount, VID, TallyStorage)
TallyLib ->> TallyLib: changeState(TallyStorage)
else
SC->>Voter: fail
end


