sequenceDiagram
participant Voter
participant EC as ElectionCommitee
participant SC as SmartContract
participant CDN
Note right of CDN: Publicly available.
Voter->>Voter: GenID(): ID
Note right of Voter: ID: PrivK + Nullifier(random) + Trapdoor(random)

Voter->>Voter: GenIDCommitment(ID): ID
Voter->>EC: IdentityCommitment
Note right of Voter: IDCommitment: H(PubK + Nullifier + Trapdoor)

EC->>EC: SetupZK(): ProvingKey, VerifKey, Circuit
EC->>EC: GenTree(IdentityCommitments) : MerkleTree
EC->>CDN: ProvingKey, VerifKey, Circuit
CDN-->>EC: CDNUrl
EC->>SC: Deploy(MerkleTree, ExtNullifier, CDNUrl)
Voter->>CDN: Request Keys
CDN-->>Voter: ProvingKey, VerifKey, Circuit
Voter->>SC: GetMerkleTree()
SC-->>Voter: MerkleTree
Voter->>SC: GetExtNullifier()
SC-->>Voter: ExtNullifier
Voter->>Voter: GenProof(VoteHash, Circuit, Identity, <br> MerkleTree, ExtNullifier): Proof
Voter->>SC: Broadcast(VoteHash, Proof, MerkleTree.root, <br> NullifierHash, ExtNullifier)
SC->>SC: Verify(VoteHash, Proof, MerkleTree.root, <br> NullifierHash, ExtNullifier)

Voter ->>SC: Reveal(VoteHash, Vote, RevealPK): VoteHash = H(Vote, RevealPK)
SC->>SC: VerifyHash(VoteHash, Vote, RevealPK)


