stateDiagram-v2
    Setup --> Register: Smart Contract Deployed
    Register --> Proposal: Manual Transition by EA
    Proposal --> Commit: ProposedCount == MaxProposalCount
    Proposal --> Commit: ProposedCount == ProposerCount
    Proposal --> Commit: BlockNumber > ProposalLifetime
    Commit --> Reveal: CommittedCount == VoterCount
    Commit --> Reveal: BlockNumber > CommitLifetime
    Reveal --> Completed: RevealedCount == CommittedCount
    Reveal --> Completed: BlockNumber > RevealLifetime


