sequenceDiagram
participant Voter
rect rgb(255, 0, 0)
note left of Voter: In Compile/Deploy State
end
participant EC as ElectionCommitee
loop For each Voter
    Voter->>Voter: GenIdentity(): Identity, IdentityCommitment
    Voter->>Voter: Store(Identity, IdentityCommitment)
rect rgb(0, 255, 153)
    Note right of Voter: Secure Channel
    Voter->>EC: IdentityCommitment
end
    EC->>EC: Store(IdentityCommitment)
end
    EC->>EC: DecideTreeLevel(VoterCount): TreeLevel
    note over EC, EC: TreeLevel = log2(TreeSize)
    EC->>EC: CompileForestZK(TreeLevel): ForestVeriferContract, ForestZKKeys, CompiledForestZK
    EC->>EC: CompileVoterZK(TreeLevel): VoterVerifierContract, VoterZKKeys, CompiledVoterZK
    Note over EC, EC: ZKKeys = ProvingKey + VerificationKey
    participant Cloud
    Note right of Cloud: Publicly available.
    EC->>Cloud: VoterZKKeys, CompiledVoterZK
    Cloud->>EC: URL
    participant SC as SmartContract
    EC->>EC: CompileContract(TreeLevel, ForestVeriferContract, VoterVerifierContract): SmartContract
    EC->> SC: DeployContract(ProposalCount, <br>  ProposalLifetime, CommitLifetime, RevealLifetime, URL)




